---
- name: Install required packages for Flask app
  yum:
    name:
      - python3
      - python3-pip
      - python3-devel
      - mysql-devel
      - gcc

- name: Install required Python packages
  pip:
    name:
      - flask
      - pymysql
  vars:
    ansible_python_interpreter: /usr/bin/python3
    executable: pip3

- name: Copy application files to webserver
  copy:
    src: /home/ec2-user/flaskapp/
    dest: /home/ec2-user/flaskapp/

- name: Ensure app.py is executable
  file:
    path: "{{ app_directory }}/app.py"
    mode: '0755'

- name: Run the Flask application
  command: python3 /home/ec2-user/flaskapp/app.py
  become_user: ec2-user 
  args:
    chdir: "/home/ec2-user/flaskapp/"
